import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { insertUserSchema, type InsertUser } from "@shared/schema";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { useToast } from "@/hooks/use-toast";
import { z } from "zod";

// Extended schema for password confirmation
const signupFormSchema = insertUserSchema.extend({
  confirmPassword: z.string().min(1, "Veuillez confirmer votre mot de passe"),
}).refine((data) => data.password === data.confirmPassword, {
  message: "Les mots de passe ne correspondent pas",
  path: ["confirmPassword"],
});

type SignupFormData = z.infer<typeof signupFormSchema>;

export default function Signup() {
  const { toast } = useToast();
  const [, setLocation] = useLocation();

  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    pseudonyme: '',
    dateOfBirth: '',
    email: '',
    phone: '',
    gender: '',
    password: '',
  });

  // Vérifier si une session d'inscription existe déjà
  useEffect(() => {
    const sessionId = localStorage.getItem("signup_session_id");
    const savedEmail = localStorage.getItem("verification_email");

    if (sessionId && savedEmail) {
      // Tenter de récupérer la session pour vérifier son état
      checkExistingSession(sessionId, savedEmail);
    }
  }, []);

  const checkExistingSession = async (sessionId: string, email: string) => {
    try {
      // Vérifier si l'utilisateur existe déjà
      const loginAttempt = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password: "dummy" }), // Password doesn't matter here
      });

      const loginResult = await loginAttempt.json();

      // Si l'utilisateur existe mais n'est pas vérifié, reprendre le processus
      if (loginAttempt.status === 403 && loginResult.requiresVerification) {
        const user = loginResult.user;

        toast({
          title: "Inscription incomplète détectée",
          description: "Reprise de votre inscription en cours...",
        });

        // Déterminer à quelle étape reprendre
        if (!user.emailVerified) {
          // Aller à la vérification email
          setLocation("/verify-email");
        } else if (!user.phoneVerified) {
          // Aller à la vérification téléphone
          localStorage.setItem("verification_phone", user.phone);
          setLocation("/verify-phone");
        }
      } else {
        // Session invalide, nettoyer
        localStorage.removeItem("signup_session_id");
        localStorage.removeItem("verification_email");
        localStorage.removeItem("verification_phone");
      }
    } catch (error) {
      // Erreur de vérification, continuer normalement
      console.log("Aucune session existante à reprendre");
    }
  };


  const form = useForm<SignupFormData>({
    resolver: zodResolver(signupFormSchema),
    defaultValues: {
      dateOfBirth: "",
      email: "",
      password: "",
      confirmPassword: "",
      phone: "",
      pseudonyme: "",
      gender: undefined,
    },
  });

  // Validation téléphone en temps réel
  const validatePhone = (phone: string) => {
    const phoneRegex = /^(\+33|0)[1-9](\d{8})$/;
    return phoneRegex.test(phone) || "Format invalide (ex: 0612345678 ou +33612345678)";
  };

  const signupMutation = useMutation({
    mutationFn: async (data: InsertUser) => {
      return apiRequest("/api/auth/signup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
    },
    onSuccess: async (response: Response) => {
      // Sauvegarder l'email pour reprendre la vérification
      localStorage.setItem("verification_email", form.getValues("email"));
      localStorage.setItem("signup_session_id", "some_session_id"); // Placeholder, should be generated by backend

      toast({
        title: "Compte créé !",
        description: "Vérifiez votre email pour continuer",
      });
      setLocation("/verify-email");
    },
    onError: (error: any) => {
      toast({
        title: "Erreur",
        description: error.message || "Une erreur est survenue lors de l'inscription",
        variant: "destructive",
      });
    },
  });

  const onSubmit = async (data: SignupFormData) => {
    const { confirmPassword, ...userData } = data;
    await signupMutation.mutateAsync(userData);
  };

  const nextStep = async () => {
    let fieldsToValidate: (keyof SignupFormData)[] = [];

    switch (step) {
      case 1:
        fieldsToValidate = ["pseudonyme"];
        break;
      case 2:
        fieldsToValidate = ["dateOfBirth"];
        break;
      case 3:
        fieldsToValidate = ["gender"];
        break;
      case 4:
        fieldsToValidate = ["email"];
        break;
      case 5:
        fieldsToValidate = ["password", "confirmPassword"];
        break;
      case 6:
        fieldsToValidate = ["phone"];
        break;
    }

    const isValid = await form.trigger(fieldsToValidate);
    if (isValid && step < 6) {
      setStep(step + 1);
    }
  };

  const prevStep = () => {
    if (step > 1) {
      setStep(step - 1);
    }
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-background px-6 py-12">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="text-5xl mb-3">☯️</div>
          <h1 className="text-3xl font-semibold text-foreground mb-2" data-testid="text-page-title">
            Créer votre compte
          </h1>
          <p className="text-sm text-muted-foreground">
            Étape {step} sur 6
          </p>
        </div>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            {/* Step 1: Pseudonyme */}
            {step === 1 && (
              <FormField
                control={form.control}
                name="pseudonyme"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-base font-medium">Pseudonyme</FormLabel>
                    <FormControl>
                      <Input
                        {...field}
                        placeholder="Votre pseudonyme"
                        className="h-12 text-base"
                        data-testid="input-pseudonyme"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {/* Step 2: Date of Birth */}
            {step === 2 && (
              <FormField
                control={form.control}
                name="dateOfBirth"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-base font-medium">Date de naissance</FormLabel>
                    <FormControl>
                      <Input
                        {...field}
                        type="date"
                        className="h-12 text-base"
                        data-testid="input-date-of-birth"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {/* Step 3: Gender Selection */}
            {step === 3 && (
              <FormField
                control={form.control}
                name="gender"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-base font-medium">Je suis</FormLabel>
                    <FormControl>
                      <div className="space-y-4">
                        {/* Section Homme */}
                        <div className="space-y-2">
                          <p className="text-sm text-muted-foreground font-medium">Homme</p>
                          <div className="grid grid-cols-2 gap-2">
                            <Button
                              type="button"
                              variant={field.value === "Mr" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mr")}
                              data-testid="button-gender-mr"
                            >
                              Hétéro
                            </Button>
                            <Button
                              type="button"
                              variant={field.value === "Mr_Homosexuel" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mr_Homosexuel")}
                              data-testid="button-gender-mr-homosexuel"
                            >
                              Gay
                            </Button>
                            <Button
                              type="button"
                              variant={field.value === "Mr_Bisexuel" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mr_Bisexuel")}
                              data-testid="button-gender-mr-bisexuel"
                            >
                              Bisexuel
                            </Button>
                            <Button
                              type="button"
                              variant={field.value === "Mr_Transgenre" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mr_Transgenre")}
                              data-testid="button-gender-mr-transgenre"
                            >
                              Transgenre
                            </Button>
                          </div>
                        </div>

                        {/* Section Femme */}
                        <div className="space-y-2">
                          <p className="text-sm text-muted-foreground font-medium">Femme</p>
                          <div className="grid grid-cols-2 gap-2">
                            <Button
                              type="button"
                              variant={field.value === "Mrs" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mrs")}
                              data-testid="button-gender-mrs"
                            >
                              Hétéro
                            </Button>
                            <Button
                              type="button"
                              variant={field.value === "Mrs_Homosexuelle" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mrs_Homosexuelle")}
                              data-testid="button-gender-mrs-homosexuelle"
                            >
                              Lesbienne
                            </Button>
                            <Button
                              type="button"
                              variant={field.value === "Mrs_Bisexuelle" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mrs_Bisexuelle")}
                              data-testid="button-gender-mrs-bisexuelle"
                            >
                              Bisexuelle
                            </Button>
                            <Button
                              type="button"
                              variant={field.value === "Mrs_Transgenre" ? "default" : "outline"}
                              className="h-12 text-sm font-semibold border-2"
                              onClick={() => field.onChange("Mrs_Transgenre")}
                              data-testid="button-gender-mrs-transgenre"
                            >
                              Transgenre
                            </Button>
                          </div>
                        </div>

                        {/* Section Professionnel */}
                        <div className="space-y-2">
                          <p className="text-sm text-muted-foreground font-medium">Professionnel</p>
                          <Button
                            type="button"
                            variant={field.value === "MARQUE" ? "default" : "outline"}
                            className="h-12 text-sm font-semibold border-2 w-full"
                            onClick={() => field.onChange("MARQUE")}
                            data-testid="button-gender-marque"
                          >
                            Compte Entreprise
                          </Button>
                        </div>
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {/* Step 4: Email */}
            {step === 4 && (
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-base font-medium">Email</FormLabel>
                    <FormControl>
                      <Input
                        {...field}
                        type="email"
                        placeholder="votre@email.com"
                        className="h-12 text-base"
                        data-testid="input-email"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {/* Step 5: Password & Confirm */}
            {step === 5 && (
              <div className="space-y-4">
                <FormField
                  control={form.control}
                  name="password"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-base font-medium">Mot de passe</FormLabel>
                      <FormControl>
                        <Input
                          {...field}
                          type="password"
                          placeholder="••••••••"
                          className="h-12 text-base"
                          data-testid="input-password"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="confirmPassword"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="text-base font-medium">Confirmer le mot de passe</FormLabel>
                      <FormControl>
                        <Input
                          {...field}
                          type="password"
                          placeholder="••••••••"
                          className="h-12 text-base"
                          data-testid="input-confirm-password"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            )}

            {/* Step 6: Phone */}
            {step === 6 && (
              <FormField
                control={form.control}
                name="phone"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-base font-medium">Téléphone</FormLabel>
                    <FormControl>
                      <Input
                        type="tel"
                        placeholder="0612345678 ou +33612345678"
                        {...field}
                        onChange={(e) => {
                          field.onChange(e);
                          const validation = validatePhone(e.target.value);
                          if (validation !== true) {
                            form.setError("phone", { message: validation });
                          } else {
                            form.clearErrors("phone");
                          }
                        }}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {/* Navigation Buttons */}
            <div className="flex gap-4 pt-4">
              {step > 1 && (
                <Button
                  type="button"
                  variant="outline"
                  onClick={prevStep}
                  className="flex-1 h-14 text-base font-semibold border-2"
                  data-testid="button-prev"
                >
                  Retour
                </Button>
              )}

              {step < 6 ? (
                <Button
                  type="button"
                  onClick={nextStep}
                  className="flex-1 h-14 text-base font-semibold"
                  data-testid="button-next"
                >
                  Suivant
                </Button>
              ) : (
                <Button
                  type="submit"
                  disabled={signupMutation.isPending}
                  className="flex-1 h-14 text-base font-semibold"
                  data-testid="button-submit"
                >
                  {signupMutation.isPending ? "Création..." : "Créer"}
                </Button>
              )}
            </div>
          </form>
        </Form>
      </div>
    </div>
  );
}